//
//  File.swift
//  WWDC22
//
//  Created by Jovinca Claudia on 17/04/22.
//

import Foundation
import SwiftUI

let story = Story(pages: [StoryPage("Mbok Arum:", text:"Hey youngin', yes you. Would you like to try some jamu? It's the beverages I'm holding right now.", choices: [Choice(text: "No mbok, I'll probably pass. Thanks for the offer though. (mbok : refers to middle-aged woman in Javanese.)", destination: 18), Choice(text: "Hmm, what is jamu exactly?", destination: 1), Choice(text: "Okay, but look at your outfit mbok, they slay!", destination: 17)], mbokImage:Image("MbokDef"), budiImage: Image("a")),
                          //1+1
                          StoryPage("Mbok Arum:", text:"Jamu is a traditional medicinal beverage from Indonesia. It is made from natural herbs, roots, leaves, bark, flowers, or seeds; and sometimes mixed with certain parts of animals or eggs. It is prevalent in Java as a lot of people, of all ages and sizes, like to drink it for its health benefit. Not to mention it also taste really good and authentic.", choices: [Choice(text: "Interesting. So, why do you have multiple bottles in your basket?", destination: 2), Choice(text: "Sounds great! What kind of health benefit are we talking about?", destination: 2), Choice(text: "Hmm, I don't really like how medicines generally taste. But I'm curious. Please tell me more", destination: 14)], mbokImage: Image("MbokTell"), budiImage: Image("a")),
                          //2+1
                          StoryPage("Mbok Arum", text: "Well, we have a lot of bottles here. Each one is a different type of jamu with different type of health benefits, tastes, and ingredients. Just mention which health concern you want to improve, and I'll recommend a jamu mix for you. I've been doing this for 35 years, so you can trust me on these!", choices: [Choice(text: "More than that, I'm rather interested in what's in these bottles", destination: 3), Choice(text: "Don't mind if I do! Let me think about which health improvement", destination: 4), Choice(text: "35 years? wow... that's amazing.", destination: 11), Choice(text: "Hmm, i wonder how far does jamu goes back in history?", destination: 10)], mbokImage: Image("MbokDelighted"), budiImage: Image("a")),
                          //3+1
                          StoryPage("Mbok Arum", text: "I see. Well, I can help explain it to you. Pick a bottle, and I'll explain it for you! You know, i'm something of a jamu expert myself. It's in the family.\n\n*There are many types of jamu, and the following option is just some examples of the popular ones*", choices: [Choice(text: "Beras kencur", destination: 19), Choice(text: "Pahitan or Brotowali", destination: 20), Choice(text: "Kunyit Asam", destination: 21), Choice(text: "Temulawak", destination: 22)], mbokImage: Image("MbokBase"), budiImage: Image("a")),
                          //4+1
                          StoryPage("Budi", text: "Afternoon Mbok Arum! I'll take the usual please, but not for me. As usual, she told me to get one of your best jamu concoction.", choices: [Choice(text: "Hey, easy there.. line up sir", destination: 5), Choice(text: "Hello there sir! Is it for your girlfriend?", destination: 6), Choice(text: " Hmm, Is it for your mother?", destination: 8)], mbokImage: Image("MbokBase"), budiImage: Image("BudiDelighted")),
                          
                          //5+1
                          StoryPage("Budi", text: "Sorry about that, you can go first.", choices: [Choice(text: "I don't really have a health concern right now. So please tell me about these bottles", destination: 3), Choice(text: "You know what? you go first", destination: 23)], mbokImage: Image("MbokConcerned"), budiImage: Image("BudiConcerned")),
                          
                          //6+1
                          StoryPage("Budi", text: "Call me Budi. But yes, it is for my girlfriend. She's on her period right now. The cramps, man... it looks painful. So she always asks for Mbok Arum's jamu to reduce her cramps, and it always works like a charm! Much expected from mbok Arum!", choices: [Choice(text: "Oooh, what kind of jamu is it?", destination: 7)], mbokImage: Image("MbokAsk"), budiImage: Image("BudiTell")),
                          
                          //7+1 ENDING 7
                          StoryPage("Good ending\nJamu Kunyit Asam for Period Cramps!", text: "\nMbok Arum told you that it's Jamu Kunyit Asam! Turmeric has analgesic properties that work to reduce pain in several parts of the body. In addition, the content of curcumin in turmeric can also inhibit the production of the prostaglandin hormone which causes inflammation and menstrual pain. That's how turmeric is considered capable of overcoming menstrual pain or abdominal cramp during menstruation.\nAlthough, it must be noted that someone who regularly consumes blood pressure medication should be careful when consuming processed turmeric.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending7")),
                          
                          //8+1
                          StoryPage("Budi", text: "Call me Budi. But yes, it is for my mother. How did you know that haha? She has got sore joints for a while now, so she asked me to get her some jamu.", choices: [Choice(text: "Just a wild guess. Anyway, what kind of jamu exactly?", destination: 9)], mbokImage: Image("MbokBase"), budiImage: Image("BudiTell")),
                          
                          //9+1 ENDING 8
                          StoryPage("Good ending\nJamu Temulawak for Sore Joint", text: "\nMbok Arum told you that it's Jamu Temulawak! This jamu can help in overcoming Osteoarthritis. The benefits of temulawak related to osteoarthritis have also been published in the Journal of Alternative and Complementary Medicine. It is said that the effect of temulawak is almost the same as the effect of ibuprofen (painkillers) given to people with osteoarthritis.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending8")),
                          //10+1
                          StoryPage("Mbok Arum", text: "Oh, honey, I'm not that well-versed in history. But I can tell you that it's very old that its traces were recorded in several old temple reliefs. Well, this business has run in my family for many years, I learned the special recipe from my grandmother. Currently, I'm passing my teachings to my grandaughter so that the business can be passed down.", choices: [Choice(text: "Awesome! Tell me more about the history and culture of jamu", destination: 24),Choice(text: "Oh my, can you spill a bit of your recipe to me?", destination: 25)], mbokImage: Image("MbokTell"), budiImage: Image("a")),
                          
                          //11+1
                          StoryPage("Budi", text: "That's right, mbok Arum is very dediated to the jamu legacy. Wait, 35 years old?.. that's even older than me, how cool is that? Anyway, I'm here since i feel a bit sick today.", choices: [Choice(text: "You have a cold?", destination: 12), Choice(text: "Hey man, sorry about your health condition. But I came here first.", destination: 5)], mbokImage: Image("MbokDelighted"), budiImage: Image("BudiDelighted")),
                          
                          //12+1
                          StoryPage("Budi", text: "Not exacly. Lately I've been getting body ache since my workload has increased for the past month. Mbok Arum, what would you reccomend for me?", choices: [Choice(text: "I see", destination: 13)], mbokImage: Image("MbokBase"), budiImage: Image("BudiTell")),
                          
                          //13+1 ENDING 11
                          StoryPage("Good ending\nCabe Puyang Jamu for Body Ache", text: "\n\"Mbok Arum reccomended consuming Cabe Puyang Jamu. This herbal medicine for aches and pains is the main benefit of getting rid of aches due to fatigue, as well as back pain. consists of chili herbs and puyang. Then add spices and other ingredients.\"", choices: [], mbokImage: Image("a"), budiImage: Image("Ending11")),
                          
                          //14+1
                          StoryPage("Mbok Arum", text: "Sure, thing! Do you have any health concern that you want to improve? Or maybe you can pick a random jamu to try. I'll let you try a bit for free!", choices: [Choice(text: "Oh I want to try the one that's called Kunyit Asam", destination: 15), Choice(text: "Oh I want to try the one in the left", destination: 15), Choice(text: "Never mind, i .. kinda changed my mind", destination: 18)], mbokImage: Image("MbokAsk"), budiImage: Image("a")),
                          
                          //15+1
                          StoryPage("Mbok Arum", text: "So how is it?", choices: [Choice(text: "Surprisingly, it tastes really pleasant! And not to mention that it is healthy too, right?", destination: 26)], mbokImage: Image("MbokConcerned"), budiImage: Image("a")),
                          
                          //16+1 ENDING 13 !!!!
                          StoryPage("Good ending\nThe Javanese Kebaya", text: "\nThis traditional outfit is called kebaya kutu baru. Other than that, we also have another kebaya type like kebaya kartini, in which the collar is v-shaped. Kebaya are usually worn along with jarik. Jarik can be worn by men or women. Jarik also have multiple batik motives on it, with it's own philosophical meaning behind it. In modern days, both Kebaya and Jarik are usually worn on special occasion like graduation day, cultural events, celebrating certain holidays, and welcoming guests. Although, some people might wear them every day as casual clothes.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending13")),
                          
                          //17+1
                          StoryPage("Mbok Arum", text: "Oh my! Thank you so much honey. Glad you noticed that. This is the traditional Javanese Kebaya. The one I'm wearing right now is Kebaya Kutu Baru", choices: [Choice(text: "Awesome!", destination: 16)], mbokImage: Image("MbokDelighted"), budiImage:Image("a")),
                          
                          //18+1 ENDING 1 BADENDING1
                          StoryPage("Bad ending\nShould've Stayed Curious", text: "\nWhat did you say to Mbok Arum? You just missed out on the special jamu insights. \n\nDon't worry, you still have another chance to explore! Tap the button bellow and try again!", choices: [], mbokImage: Image("a"), budiImage: Image("Ending1")),
                          
                          //19+1 ENDING 2
                          StoryPage("Good ending\nBeras Kencur!", text: "\nBeras kencur, which directly translates to rice and sand ginger, consists of sand ginger, rice, aromatic ginger, and tamarind extract. Its sweet and fresh taste is suitable for many. This jamu also tastes a bit spicy, thus representing the slight spicy taste of an adolescent who just experienced the real world. Beras kencur has a high antioxidant activity which is believed to have many benefits for maintaining a healthy body, including controlling weight, increasing appetite, eliminating aches and pains, increasing stamina, as an anti-diabetic, and controlling weight.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending2")),
                          
                          //20+1 ENDING 3
                          StoryPage("Good ending\nPahitan or Brotowali!", text: "\n\"Brotowali\" refers to javanese heart-leaved moonseed. Philosophically, it represents a certain bitter stage of life that we must conquer. Just like the jamu itself. No matter how bitter it is, you must swallow it. The main ingredient for this is green chiretta leaf (Sambiloto leaf). The side materials for this jamu vary according to your own preference, some prefer a more bitter taste by adding more bitter ingredients like brotowali itself. As the name suggests, this jamu is considered the most bitter jamu. It is believed to have many benefits ranging from overcoming aches, itching, increasing appetite, preventing the risk of diabetes, dialysis therapy, and anti-allergy. Fans of this bitter herbal medicine are mostly old people. But, there are also young people who consume it because it helps getting rid of acne and pimples.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending3")),
                          
                          //21+1 ENDING 4
                          StoryPage("Good ending\nKunyit Asam!", text: "\nKunyit Asam, which directly translates to Turmeric Tamarind, is usually the most sought-after jamu. The sweet and sour taste of this jamu philosophically represents the sweet stage of life, going from an infant to an adolescent. The main ingredients of this Kunyit Asam herbal medicine are turmeric and tamarind. The additional ingredients are brown sugar, ginger, and other spices. Tamarind contains a compound that functions as an analgesic or anti-pain anthocyanins. According to a study, Kunyit Asam can reduce primary menstrual pain. It can also brighten up the skin since turmeric contains many antioxidants that help rejuvenate body cells.\n\n *A study by Studi Kebidanan D3 Stikes Harapan Bangsa Purwokerto.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending4")),
                          
                          //22+1 ENDING 5
                          StoryPage("Good ending\nTemulawak!", text: "\nJamu Temulawak is made of temulawak itself and some other ingredients such as tamarind, palm sugar, pandan leaves, and cumin. It is believed that it can cure health concerns like dizziness, nausea, and stomach pain, and relieve symptoms of colds. Temulawak itself contains antioxidants that can prevent cell damage to the gastric mucosa due to its free radicals. The compounds that act as antioxidants from this jamu are flavonoids, phenols, and curcumin.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending5")),
                          
                          //23+1 ENDING 6 BADENDING2
                          StoryPage("Bad ending\n\"No, You go first!\" loop", text: "\nYou see, Budi is trying to be polite. Mbok Arum immediately left the scene as she don't want to get involved in the loop. Both of you didn't even realize that mbok Arum was leaving and continued the loop.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending6")),
                          
                          //24+1 ENDING 9
                          StoryPage("Good ending\nTime for history class!", text: "\nMbok Arum enthusiastically explained to you about  jamu's cultural history and heritage. Here is the note that you took :\n\n Jamu is a term that comes from the Javanese language, precisely in 16 AD. The word Jamu comes from two words, namely \"Djampi\" and \"Oesodo\" which means medicine, prayer, and formula that sounds magical. Jamu first appeared during the Mataram Kingdom or about 1300 years ago. The existence of herbal medicine since ancient times can be seen from some historical evidence such as the reliefs on the Borobudur temple which was made around 772 AD. The reliefs depict the habit of mixing and drinking herbal medicine to maintain health.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending9")),
                          
                          //25+1 ENDING 10
                          StoryPage("Good ending\nSecret Kunyit Asam Recipe!", text: "\nDon't go anywhere asking for people's secret recipe (you can look it up the on the internet too). But since mbok Arum is very thoughtful and kind, she shared one of her secret recipes with you. (For 5 servings)\n\n Kunyit, the old one(Turmeric) - 400 gram\n Gula jawa (Palm sugar) - 250 gram\n Asam jawa (Javanese tamarind) - 100 gram\n Warm water, to dip the tamarind in  - 100 ml\n Water - 2 liter\n\n 1. Soak the tamarind in warm water. Squeeze and set aside.\n 2. Burn the turmeric until it turns slightly brown. Peel the turmeric, then wash, and cut into small pieces.\n 3. Blend turmeric with 500 ml of water.\n 4. In a saucepan, mix the tamarind water, turmeric blend, and the remaining 1.5 liters of water. Then, boil the mixture until it reaches a full boil.\n 5. Add palm sugar. Stir well and boil it again until it reaches a full boil.\n 6. Turn off the heat, let the herbs cool down, then strain them.\n 7. Jamu is ready to be served.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending10")),
                          
                          //26+1 ENDING 12
                          StoryPage("Good ending\nMbok Arum's Concern", text: "\nMbok : Arum said : \"Of course! It's nice to see people enjoying my jamu. You see, some youngsters these days don't really like them. They don't understand the culture and health benefits of jamu that have been passed down from generation to generation\". As modernization goes on, the younger generation generally has less interest in jamu. There is a common misconception that only sick people consume jamu, although that is not always the case as jamu has multiple types and distinct benefits.\n\n On the bright side, jamu has also been introduced to the international world in an attempt to spread and conserve the legacy of this herbal medicine.", choices: [], mbokImage: Image("a"), budiImage: Image("Ending12"))
                          
                         ])
